const MOODS = [
  {
    emoji: "😊",
    label: "Happy",
    color: "#F6C944",
    bg: "linear-gradient(135deg, #FFF7D6 0%, #FFE89A 50%, #F6C944 100%)",
    musicConfig: {
      notes: ["C4", "E4", "G4", "B4", "D5", "E5"],
      tempo: 132,
      synthType: "bright",
      pad: ["Cmaj7", "Fmaj7", "Am7", "G7"],
      key: "C major",
    },
  },
  {
    emoji: "😢",
    label: "Sad",
    color: "#5B8DEF",
    bg: "linear-gradient(135deg, #D6E6FF 0%, #A3C4F3 50%, #5B8DEF 100%)",
    musicConfig: {
      notes: ["A3", "C4", "E4", "G4", "A4", "C5"],
      tempo: 68,
      synthType: "warm",
      pad: ["Am", "F", "C", "G"],
      key: "A minor",
    },
  },
  {
    emoji: "😤",
    label: "Angry",
    color: "#E85D4A",
    bg: "linear-gradient(135deg, #FFD6D1 0%, #F4A39A 50%, #E85D4A 100%)",
    musicConfig: {
      notes: ["D3", "F3", "A3", "C4", "D4", "F4"],
      tempo: 92,
      synthType: "dark",
      pad: ["Dm", "Bb", "Gm", "A"],
      key: "D minor",
    },
  },
  {
    emoji: "😰",
    label: "Anxious",
    color: "#9B7FE6",
    bg: "linear-gradient(135deg, #E8DFFF 0%, #C4B1F0 50%, #9B7FE6 100%)",
    musicConfig: {
      notes: ["F3", "A3", "C4", "E4", "F4", "A4"],
      tempo: 60,
      synthType: "ethereal",
      pad: ["Fmaj7", "Dm7", "Bbmaj7", "C7"],
      key: "F major",
    },
  },
  {
    emoji: "😴",
    label: "Tired",
    color: "#7BAFD4",
    bg: "linear-gradient(135deg, #D6ECF5 0%, #A8D4E8 50%, #7BAFD4 100%)",
    musicConfig: {
      notes: ["Eb3", "G3", "Bb3", "D4", "Eb4", "G4"],
      tempo: 52,
      synthType: "dreamy",
      pad: ["Ebmaj7", "Cm7", "Abmaj7", "Bb7"],
      key: "Eb major",
    },
  },
  {
    emoji: "🤩",
    label: "Excited",
    color: "#FF7EB3",
    bg: "linear-gradient(135deg, #FFE0ED 0%, #FFB3D1 50%, #FF7EB3 100%)",
    musicConfig: {
      notes: ["G3", "B3", "D4", "F#4", "G4", "B4"],
      tempo: 140,
      synthType: "bright",
      pad: ["G", "D", "Em", "C"],
      key: "G major",
    },
  },
  {
    emoji: "😐",
    label: "Numb",
    color: "#A0A8B4",
    bg: "linear-gradient(135deg, #E8EAED 0%, #C8CDD4 50%, #A0A8B4 100%)",
    musicConfig: {
      notes: ["E3", "G3", "B3", "D4", "E4", "G4"],
      tempo: 56,
      synthType: "ethereal",
      pad: ["Em7", "Cmaj7", "Am7", "Bm7"],
      key: "E minor",
    },
  },
  {
    emoji: "🥰",
    label: "Loved",
    color: "#E87DA0",
    bg: "linear-gradient(135deg, #FFE0EA 0%, #F2B0C4 50%, #E87DA0 100%)",
    musicConfig: {
      notes: ["Ab3", "C4", "Eb4", "G4", "Ab4", "C5"],
      tempo: 78,
      synthType: "warm",
      pad: ["Abmaj7", "Fm7", "Dbmaj7", "Eb7"],
      key: "Ab major",
    },
  },
  {
    emoji: "😶‍🌫️",
    label: "Lost",
    color: "#8CA3B8",
    bg: "linear-gradient(135deg, #E0EAF0 0%, #B4C8D8 50%, #8CA3B8 100%)",
    musicConfig: {
      notes: ["B3", "D4", "F#4", "A4", "B4", "D5"],
      tempo: 58,
      synthType: "dreamy",
      pad: ["Bm7", "Gmaj7", "Em7", "F#m7"],
      key: "B minor",
    },
  },
];

export default MOODS;
